### ISSUE TITLE
Crashes on Firefox when committing changes

### ISSUE THREAD

**Issue by swertz** [cms-PdmV/cmsPdmV#1080]
Hello,
Recently my McM tabs have started to crash frequently with Firefox (84.0), in particular when I commit changes for a multiple selection of requests. It looks like a memory leak (the OS kills the tabs' threads because there's no memory left)... could it be due to the "winter snow feature"?

**Comment by justinasr** [comment]
Hello,
It crashes only when you click "Commit" after editing multiple requests? Does the same happen when committing single request? How many requests are you trying to edit at once and which attributes (sequences, time/event, etc.)? If you don't mind, a couple of prepids would be helpful as well. I'll need to reproduce it myself, so far no luck on FF 78.6esr.
I doubt that it's because of "snow" as it is in every single page and even if it leaks memory, I would assume this would cause a crash after keeping a tab open for hours or days.

**Comment by swertz** [comment]
> It crashes only when you click "Commit" after editing multiple requests? Does the same happen when committing single request?

If I remember correctly all the times it happened, only when editing multiple requests and after clicking "commit".

> How many requests are you trying to edit at once and which attributes (sequences, time/event, etc.)?

As few as two and as many as 12. The attributes were time/event and/or adding a customize_command to the sequences.

Note that while the tabs crashed, the requests were actually successful and the changes applied.

> If you don't mind, a couple of prepids would be helpful as well.

Here are some examples: https://cms-pdmv.cern.ch/mcm/requests?prepid=TOP-RunIISummer20UL16GENAPV-*&page=0&shown=127
However they are now either validating or validated, so we can't try to reproduce. If the validations fail (which happens a lot with these prepids) I'll ping here before re-launching them!

**Comment by swertz** [comment]
It's just happened again, while I was editing the time/event for selected prepids `TOP-RunIISummer20UL18GEN-00010` and `TOP-RunIISummer20UL18GEN-00012`.
After clicking "commit" the request took a long time (~2 minutes) then then the tab crashed, but the new value was saved correctly.
I'll wait before triggering validation in case you'd like to try.

**Comment by swertz** [comment]
It seems to work better now, and I really need to get the validation going, so I'll close this for now...
