### ISSUE TITLE
lists/update creating duplicate documents

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#1154]
I queried the lists update api via mcm rest library with 

```
doc={ "prepid" : "list_of_forcecomplete", "value" : ["BPH-RunIISummer20UL18MiniAODv2-00423","TRK-Phase2Fall22DRMiniAOD-00008"]}

mcm.put('lists', doc, method='update')
```

and it created another list call "list_of_forcecomplete" instead of updating the one in place.

**Comment by ggonzr** [comment]
The application uses the field `_id` as "primary key", not the field `prepid`. Also it requires the field `_rev` to check it is working on the most recent version of the document. Because both of the fields described are not provided, it attempts to create another document. To properly update the document, retrieve it first, modify its content and then use it to update on the database. Following the example provided, it would be:

```python
from rest import McM

# McM instance
mcm = McM(id=McM.OIDC, dev=True)
list_force_complete = mcm.get(object_type="lists", object_id="list_of_forcecomplete")

# Update the list
new_requests = ["BPH-RunIISummer20UL18MiniAODv2-00423", "TRK-Phase2Fall22DRMiniAOD-00008"]
new_force_complete = list_force_complete.get("value", []) + new_requests
list_force_complete["value"] = new_force_complete

# Send the update
mcm.update(object_type="lists", object_data=list_force_complete)
```

**Comment by vlimant** [comment]
yes, the example you provided is what I eventually did. 
the code in `class UpdateList(RESTResource):` should have a protection to check on _id, etc to update and not create a new object. (which begs the question "how do we create a new list?", but that should be left for dev, not admin)

**Comment by ggonzr** [comment]
Including a new list would also require updates in the [frontend](https://github.com/cms-PdmV/cmsPdmV/blob/52a6b7e7820702293b965aa360d903fde30e7ce2/mcm/scripts/lists_controller.js#L31-L76) side to properly display its content, so I think it is not required to include another endpoint to automatically include a new list in the application.
