### ISSUE TITLE
variable 'executor' referenced before assignment

### ISSUE THREAD

**Issue by AdrianAlan** [cms-PdmV/cmsPdmV#725]
Traceback (most recent call last):
File \"/home/mcm/cmsPdmV/mcm/tools/handlers.py\", line 470, in internal_run
executor.close_executor()
UnboundLocalError: local variable 'executor' referenced before assignment

Problem when try ends here:
https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/tools/handlers.py#L395

Moving assignment up from L398 to L394 will solve problem. However the code was last changed in March, so it's first time since at least 9 months that the check_request returns false. Thus it's interesting to know why those requests are failing: B2G-Phys14DR-00061, B2G-Phys14DR-00063 etc.

Excample of history:
approve     2014-12-18-04-26    PdmV Service    submit
inject  2014-12-18-13-21    automatic   flow...
set status 2014-12-18-13-21     automatic   submitted
failed  2014-12-18-13-21    automatic

Also, why between 'approve' and 'inject' requests hangs there for 9h while B2G-Phys14DR-00060 changes status immediately. There has been some manual interaction before the 'failed' status. I will get back as soon as I get more info.

**Comment by anorkus** [comment]
Hi,

@vlimant  aren't you confusing saying that request flow is forked 1st and then requestInspect is triggered immediately?

"in the first place : forking of inspection should not have been done" -> there is no forking of inspection;

"Roll out the forking of inspection otherwise some good indicator should be found to prevent requestinspect to go before flow is done" -> there is no forking of inspection... It is done only for request Flow.

As it was from beginning : RequestInspect is triggered in jenkins; it finishes; then the request flow is forked out (it runs usually ~15mins);

There is other issue that RequestInspection times out and crashes silently without finishing (jenkins sees it as success) and launches RequestFlow. But this is a problem that RequestInspection has no forking

**Comment by vlimant** [comment]
Please remind yourself both issues and convince yourself that I am not confusing anything.
