### ISSUE TITLE
Users unable to access sequences

### ISSUE THREAD

**Issue by davidsheffield** [cms-PdmV/cmsPdmV#728]
Users are unable to view the sequences for requests. Using Select View, they can view the sequences column in McM. But when they click on the eye to view the actual cmsDriver.py sequence, they get a prompt saying only "Error" rather than the sequence appearing. This does not happen to me with generator contact permissions. Can this behavior be changed so that users are able to easily check the sequences used for requests without?

**Comment by anorkus** [comment]
hi,
thanks for reporting this. This error happens if the user in not in McM DB and it tries to get user credentials. Easiest would be to go to users page and just register (by clicking "Add me") button. In this way people would be with users but known to McM DB.
In any case i will develop a fix for people who are browsing without any registration with user rights.

**Comment by davidsheffield** [comment]
Thanks. I passed this on to the person trying to get the sequences and they were able to get access to them after registering.

**Comment by anorkus** [comment]
fixed in https://github.com/cms-PdmV/cmsPdmV/commit/dea16538edef443e4a56495d1e7d1b5d9fd6f7e9
