### ISSUE TITLE
Confusion of process_string with taskchain request

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#741]
Today, I test the request from Josh, to have
--inputCommands 'keep _','drop LHEXMLStringProduct___*_*’
for the flows from wmLHE to GS/GenOnly.

What I’ve done is to modify the flows listed here,
https://cms-pdmv.cern.ch/mcm/flows?prepid=flowRunIIWinter15wmLHEto*&page=0&shown=255.
Then I put the "process_string : 15March2015" in these two flows.

After that, I create one taskchain request,
https://cms-pdmv.cern.ch/mcm/chained_requests?contains=TOP-RunIIWinter15wmLHE-00010&page=0&shown=15

When I try to validate the chain, McM doesn’t allow me to validate the chain because of
“It is illegale to approve validation in status new. The sequences of the request has been changed with respect to the campaign, but no processing string has been provided"

I then put the process_string again in the GenOnly request directly,
https://cms-pdmv.cern.ch/mcm/requests?prepid=TOP-RunIIWinter15GenOnly-00001&page=0&shown=268435917951
Now McM allows me to validate this chain.

Do you have an idea why I need to put it again? Do I miss something?

**Comment by vlimant** [comment]
Hi Phat,
 The process string from the flow (which does not get added to the request object, but only at submission time)  is not taken into account in the sequence modification check, as you noticed. Including it in the check is rather trivial.

**Comment by vlimant** [comment]
Having a meaningful process string is a generic recommendation

**Comment by srimanob** [comment]
@vlimant Thanks.
So for this wmLHE, should we set only in the request? @bendavid

**Comment by bendavid** [comment]
I'm not sure I got the point.  These inputcommands have 0 effect on the output, so ideal would be to have no process string at all.  Of there needs to be a process string (presumably only for the gensim or genonly request) then it had better be set automatically, otherwise we'll have huge confusion/mistakes/different strings.

**Comment by vlimant** [comment]
The protection in mcm for sequence/process string is there as a protection, indeed some of the sequence modifications (as current example) have no modification to the output (note that it does, as there is a missing product) and wiring add-hoc switches would be tedious IMO.
Implementing the flow process string in the check is what you are suggesting.

**Comment by bendavid** [comment]
No this product is anyways dropped from the output.  Dropping also on input dimply saves memory.

**Comment by vlimant** [comment]
The comment holds, just remove things in parenthesis ;-)

**Comment by bendavid** [comment]
Ok, I understood the issue now I think.

The process string is required by design in the case of flows which customize the sequence with respect to the campaign.  The process string CAN be defined at the flow level and will be automatically added to the requests, but the automated check does not take this into account, currently requiring the process string to be set manually for the request.  Did I get it right?  If so then agreed that the minimal solution of implementing this in the check is the way to go.

**Comment by vlimant** [comment]
e28145d56ca85be41b499c907e800ade26b7655b closes it
