### ISSUE TITLE
failing set of instructions in GenOnly campaign

### ISSUE THREAD

**Issue by govoni** [cms-PdmV/cmsPdmV#795]
To whom it may concern, if I try to follow these instructions I get a failure, since the " --filein" field is missing in the cmsDriver command.

https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/HIG-RunIIWinter15GenOnly-00001

pietro

**Comment by govoni** [comment]
Are there any news on this?

**Comment by srimanob** [comment]
@govoni 
The situation can be described as
+ First, the request was in taskchain. If wmLHE + GS are in new status, you will get the proper test script from the chain request page https://cms-pdmv.cern.ch/mcm/public/restapi/chained_requests/get_test/HIG-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGenOnly-00002

+ That's a reason that you don't see --filein in the test script (because there is no input since the beginning).

+ However, the WMLHE + GS are done, and the "current step" (* icon in chain request page) moves to GS, so the test script you will get from chain_request page will also be wrong. I think it uses reference from "current step" of the chain to be a starting point.

+ The only way now is you first get test script from WMLHE request, run it. Then add --filein to test script from GS manually. Or add --filein from existing dataset manually.

**Comment by srimanob** [comment]
@anorkus  
I think we can close this, or consider to improve the test script generator in McM.
