### ISSUE TITLE
prevent submit if pending invalidations

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#880]
in some cases the invalidation is announced after a resubmission happened and that invalidates dataset being produced.
it might be worth checking that there are no "new"/"announced" pending invalidation for a given prepid before letting the injection go.

looks to me it happened on that one https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-PhaseIITDRSpring17DR-00034

**Comment by anorkus** [comment]
the reset increases request's version, which then generates different output. So technically the announcement after resubmission should only affect old dataset (version-1).

**Comment by vlimant** [comment]
there is an async in what goes in the invalidations document and what is visible in reqmgr, so preventing the invalidation post-resubmission will prevent setting invalid things in production and creating extra delays.

**Comment by anorkus** [comment]
well, but what causes the issue. because with the reset there will be 2 invalidation documents (1 - dataset, 2- workflow). With the reset the request version increases, and so the dataset's. I imagine you either remove workflow and delete the dataset (version-1) from system, which means the newest dataset is not touched. I'm still puzzled how this caused issues as dataset_name & workflow are unique

**Comment by vlimant** [comment]
workflow and dataset invalidation are decoupled so that one can be done without the other, hence a possible async
