### ISSUE TITLE
Missing parent datasets in McM when multiple chain requests are submitted together as taskchain

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#933]
Parents does not show up properly when we inject as a taskchain for multiple chain requests:

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_JME-RunIIFall18GS-00003

https://cms-pdmv.cern.ch/mcm/requests?dataset_name=QCD_Pt-15to7000_TuneCP5_Flat_13TeV_pythia8&page=0&status=done&shown=311924099199&member_of_campaign=*Fall18*

**Comment by justinasr** [comment]
Indeed. Just my comment:
Explanation: Input datasets are set only when chained request flows and previous request has output dataset. Output dataset is reveived from Stats (from ReqMgr2). So when whole chain of requests is created in one go, it does not set InputDataset because none of them have OutputDatasets because they haven't been submitted yet.
Solution: In my opinion, input dataset can be refreshed from time to time, maybe when output dataset for previous request is updated.

**Comment by justinasr** [comment]
Fixed, pull request: #938
