### ISSUE TITLE
Checking (again) the efficiency formula

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#984]
We should check what happens for this request which does not get validated. (sorry, I thought I had opened it already)

Is the efficiency uncertainty really 0?

Request is 
https://cms-pdmv.cern.ch/mcm/requests?prepid=BPH-RunIIFall17GS-00135&page=0&shown=127

------------------------------------ GenXsecAnalyzer:
------------------------------------ Before Filter: total cross section
= 5.459e+08 +- 4.234e+06 pb

Filter efficiency (taking into account weights)= (2) / (16457) =
1.215e-04 +- 8.593e-05

Filter efficiency (event-level)= (2) / (16457) = 1.215e-04 +- 8.593e-05
[TO BE USED IN MCM]

[5] For the request BPH-RunIIFall17GS-00135 measured efficiency was not
withing set threshold.

McM validation test measured 0.0001 efficiency.

There were 16457 trial events, of which 2 passed filter/matching.

User provided efficiency 0.0001 * 1.0000 = 0.0001.

McM threshold is 0.0001 +- 0.0000.

**Comment by justinasr** [comment]
McM uses all digits after decimal point when calculating this, but it rounds up to 4 digits when sending an email (otherwise 0.3 would be 0.3000000001 or similar). The newest email that I have is: McM validation test measured 0.0001 efficiency. There were 92160 trial events, of which 10 passed filter/matching. User provided efficiency 0.0001. Let's try to calculate with more digits:

10 / 92160 = 0.00010850694 (McM measured)
0.0001 (User provided)
sigma = (measured_efficiency * (1 - measured_efficiency)) / events_ran = ((10 / 92160) * (1 - 10/92160)) / 92160 = 0.00010849517 / 92160 = 0.00000000117724794
if sigma < 0.00010850694 * 0.02: sigma = 0.00010850694 * 0.02 = 0.00000217013
sigma = 0.00000217013
three_sigma = 0.00010850694 * 3 * 0.02 = 0.00000651041
So according to user and +- 3 sigma, efficiency should be between
**0.00009348959**
and
**0.00010651041**
but is
**0.00010850694**
It's too high by
**0.00000199653**

Just so it would be easier to see, if you move decimal point by 3 places to the right, you get:
_So according to user and +- 3 sigma, efficiency should be between_
_0.09348959_
_and_
_0.10651041_
_but is_
_0.10850694 (too high by 0.00199653)_

I used google as calculator, feel free to recalculate, but I think this is the problem. I can increase number of significant digits in email.
NOTE: `filter efficiency error` and `match efficiency error` are not used in calculations of "User provided efficiency", only `filter efficiency` and `match efficiency` are (`user_provided = filter efficiency * match efficiency`

**Comment by pgunnell** [comment]
Hi Justinas, thanks. I see. I would then increase the minimum uncertainty for the sigma. Now it's at 2%, I would put it at 5% (and change the digits in the log, so that the MC contacts can directly compare the discrepancy of the numbers).

if sigma < user_provided * 0.05: sigma = user_provided * 0.05

**Comment by qliphy** [comment]
@justinasr   I have a simple question on "sigma = (measured_efficiency * (1 - measured_efficiency)) / events_ran"

Should it instead be sigma = sqrt((measured_efficiency * (1 - measured_efficiency)) / events_ran)  ?
（see e.g. [ref here](http://home.fnal.gov/~paterno/images/effic.pdf#page=3&zoom=200,-6,499)）

If so, then in your example the sigma should be 0.00003431104

**Comment by pgunnell** [comment]
Hi Qiang! good catch! definitely yes!
